// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: People.proto

package com.todo.netty.demo6.proto;

public interface StreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.todo.demo6.proto.StreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response_info = 1;</code>
   */
  String getResponseInfo();
  /**
   * <code>string response_info = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseInfoBytes();
}
