// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: People.proto

package com.todo.netty.demo6.proto;

public interface StreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.todo.demo6.proto.StreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request_info = 1;</code>
   */
  String getRequestInfo();
  /**
   * <code>string request_info = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestInfoBytes();
}
