// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: People.proto

package com.todo.netty.demo6.proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.todo.demo6.proto.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.todo.demo6.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<StudentResponse>
      getStudentResponseList();
  /**
   * <code>repeated .com.todo.demo6.proto.StudentResponse studentResponse = 1;</code>
   */
  StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .com.todo.demo6.proto.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .com.todo.demo6.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends StudentResponseOrBuilder>
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .com.todo.demo6.proto.StudentResponse studentResponse = 1;</code>
   */
  StudentResponseOrBuilder getStudentResponseOrBuilder(
          int index);
}
