// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: People.proto

package com.todo.grpc.demo6.proto;

public interface MyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.todo.grpc.demo6.proto.MyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
