// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: People.proto

package com.todo.grpc.demo6.proto;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_todo_grpc_demo6_proto_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_todo_grpc_demo6_proto_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_todo_grpc_demo6_proto_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_todo_grpc_demo6_proto_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_todo_grpc_demo6_proto_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_todo_grpc_demo6_proto_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_todo_grpc_demo6_proto_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_todo_grpc_demo6_proto_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_todo_grpc_demo6_proto_StudentResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_todo_grpc_demo6_proto_StudentResponseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_todo_grpc_demo6_proto_StreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_todo_grpc_demo6_proto_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_todo_grpc_demo6_proto_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_todo_grpc_demo6_proto_StreamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014People.proto\022\031com.todo.grpc.demo6.prot" +
      "o\"\035\n\tMyRequest\022\020\n\010username\030\001 \001(\t\"\036\n\nMyRe" +
      "sponse\022\020\n\010realname\030\002 \001(\t\"\035\n\016StudentReque" +
      "st\022\013\n\003age\030\001 \001(\005\":\n\017StudentResponse\022\014\n\004na" +
      "me\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\014\n\004city\030\003 \001(\t\"Z\n\023S" +
      "tudentResponseList\022C\n\017studentResponse\030\001 " +
      "\003(\0132*.com.todo.grpc.demo6.proto.StudentR" +
      "esponse\"%\n\rStreamRequest\022\024\n\014request_info" +
      "\030\001 \001(\t\"\'\n\016StreamResponse\022\025\n\rresponse_inf" +
      "o\030\001 \001(\t2\306\003\n\016StudentService\022f\n\025getRealNam",
      "eByUserName\022$.com.todo.grpc.demo6.proto." +
      "MyRequest\032%.com.todo.grpc.demo6.proto.My" +
      "Response\"\000\022m\n\020getStudentsByAge\022).com.tod" +
      "o.grpc.demo6.proto.StudentRequest\032*.com." +
      "todo.grpc.demo6.proto.StudentResponse\"\0000" +
      "\001\022x\n\027getStudentsWrapperByAge\022).com.todo." +
      "grpc.demo6.proto.StudentRequest\032..com.to" +
      "do.grpc.demo6.proto.StudentResponseList\"" +
      "\000(\001\022c\n\006BiTalk\022(.com.todo.grpc.demo6.prot" +
      "o.StreamRequest\032).com.todo.grpc.demo6.pr",
      "oto.StreamResponse\"\000(\0010\001B+\n\031com.todo.grp" +
      "c.demo6.protoB\014StudentProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_todo_grpc_demo6_proto_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_todo_grpc_demo6_proto_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_todo_grpc_demo6_proto_MyRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_com_todo_grpc_demo6_proto_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_todo_grpc_demo6_proto_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_todo_grpc_demo6_proto_MyResponse_descriptor,
        new java.lang.String[] { "Realname", });
    internal_static_com_todo_grpc_demo6_proto_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_todo_grpc_demo6_proto_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_todo_grpc_demo6_proto_StudentRequest_descriptor,
        new java.lang.String[] { "Age", });
    internal_static_com_todo_grpc_demo6_proto_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_todo_grpc_demo6_proto_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_todo_grpc_demo6_proto_StudentResponse_descriptor,
        new java.lang.String[] { "Name", "Age", "City", });
    internal_static_com_todo_grpc_demo6_proto_StudentResponseList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_todo_grpc_demo6_proto_StudentResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_todo_grpc_demo6_proto_StudentResponseList_descriptor,
        new java.lang.String[] { "StudentResponse", });
    internal_static_com_todo_grpc_demo6_proto_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_todo_grpc_demo6_proto_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_todo_grpc_demo6_proto_StreamRequest_descriptor,
        new java.lang.String[] { "RequestInfo", });
    internal_static_com_todo_grpc_demo6_proto_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_todo_grpc_demo6_proto_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_todo_grpc_demo6_proto_StreamResponse_descriptor,
        new java.lang.String[] { "ResponseInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
