// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: People.proto

package com.todo.grpc.demo6.proto;

public interface StudentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.todo.demo6.proto.StudentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   */
  int getAge();
}
